export enum EFlaggedReason {
	DELETED = 'DELETED',
	EDITED = 'EDITED',
	MOD = 'MOD_FLAGGED',
	AUTOMOD = 'AUTOMOD_FLAGGED'	,
};

export enum EMediaSaveReason {
	FLAGGEDMESSAGE = 'FLAGGED_MESSAGE',
	AUTOMODFLAGGED = 'AUTOMOD_FLAGGED',
	MODFLAGGED = 'MOD_FLAGGED',
};