on:
  push:
    branches:
      - '**'
jobs:
  lint:
    runs-on:
      - ubuntu-latest
    steps:
    - name: Yarn setup
      uses: DerYeger/yarn-setup-action@master
      with:
        node-version: 16

    - name: install dependencies
      run: pnpm install

    - name: lint
      run: pnpm lint
