on:
  push:
    branches:
      - '**'
jobs:
  Lint_check:
    runs-on:
      - ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: enable corepack
      run: corepack enable
    - uses: actions/setup-node@v4
      with:
          node-version: '20'
          cache: 'yarn'
    - name: setup yarn
      run: corepack enable
    - name: yarn set version
      run: yarn set version stable
    - name: yarn install
      run: yarn install --frozen-lockfile
    - name: run lint
      run: yarn lint

  format_check:
    runs-on:
      - ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: enable corepack
      run: corepack enable
    - uses: actions/setup-node@v4
      with:
          node-version: '20'
          cache: 'yarn'
    - name: setup yarn
      run: corepack enable
    - name: yarn set version
      run: yarn set version stable
    - name: yarn install packages
      run: yarn install --frozen-lockfile
    - name: execute prettier
      run: yarn exec prettier -c .
