on:
  push:
    branches:
      - '**'
jobs:
  Lint_check:
    runs-on:
      - ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: enable corepack
      run: corepack enable
    - uses: actions/setup-node@v4
      with:
          node-version: '20'
          cache: 'pnpm'
    - name: setup yarn
      run: corepack enable
    - name: pnpm install
      run: pnpm i
    - name: run lint
      run: pnpm lint

  format_check:
    runs-on:
      - ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: enable corepack
      run: corepack enable
    - uses: actions/setup-node@v4
      with:
          node-version: '20'
          cache: 'pnpm'
    - name: setup yarn
      run: corepack enable
    - name: yarn install packages
      run: pnpm i --frozen-lockfile
    - name: execute prettier
      run: pnpm exec prettier -c .
