on:
  push:
    branches:
      - '**'
jobs:
  prep:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: enable corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: setup yarn
        run: corepack enable
      - name:
        run: yarn set version stable
      - name:
        run: yarn install --frozen-lockfile
      - uses: actions/upload-artifact@v4
        with:
          name: codebase
          path: /home/runner/work/droneBeeBot/droneBeeBot/ # or path/to/artifact

  Lint_check:
    runs-on:
      - ubuntu-latest
    needs: prep
    steps:
    - uses: actions/download-artifact@v4
    - uses: actions/setup-node@v4
      with:
          node-version: '20'
          cache: 'yarn'
    - name: setup yarn
      run: corepack enable
    - name:
      run: yarn set version stable
    - name:
      run: yarn install --frozen-lockfile
    - name: run
      run: yarn lint

#   format_check:
#     runs-on:
#       - ubuntu-latest
#     needs: prep
#     steps:
#       - name:
#         run: yarn exec prettier -c .

